version: "3.9"

services:

  python:
    container_name: python
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  awslocal:
    container_name: awslocal
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,lambda,iam,logs
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=fake
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
